esphome:
  name: lilygo
  friendly_name: lilygo e-ink display

  platformio_options:
    upload_speed: 921600
    monitor_speed: 115200
    board_build.mcu: esp32s3
    board_build.f_cpu: 240000000L
    board_build.arduino.memory_type: qspi_opi
    board_build.flash_size: 4MB
    board_build.flash_mode: qio
    board_build.flash_type: qspi
    board_build.psram_type: opi
    board_build.memory_type: qspi_opi
    board_build.boot_freq: 80m
    build_flags:
      - "-DBOARD_HAS_PSRAM"
      - "-DARDUINO_USB_CDC_ON_BOOT=1"
      - "-mfix-esp32-psram-cache-issue"

  libraries:
    - SPI

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    # CRITICAL for ESP-IDF 5.4.2+: Enable PSRAM initialization (thanks @hbast!)
    sdkconfig_options:
      CONFIG_SPIRAM: "y"
      CONFIG_SPIRAM_MODE_OCT: "y"
      CONFIG_SPIRAM_SPEED_80M: "y"
      CONFIG_SPIRAM_USE_MALLOC: "y"
      CONFIG_SPIRAM_MALLOC_ALWAYSINTERNAL: "16384"
      CONFIG_SPIRAM_TRY_ALLOCATE_WIFI_LWIP: "y"
      CONFIG_ESP32S3_SPIRAM_SUPPORT: "y"
      CONFIG_SPIRAM_BOOT_INIT: "y"
      CONFIG_SPIRAM_IGNORE_NOTFOUND: "n"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "uji41VdMORB5966gRlVYEbBaC5LU9NZwHStB8j2d/nU="

ota:
  - platform: esphome
    password: "4ab30fdd89bd61087359d5eebf85d296"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Lilygo Fallback Hotspot"
    password: "zYQIOsSr8spF"

captive_portal:

external_components:
  - source: github://dabalroman/esphome-lilygo-t547plus_esphome-2025.11
    components: ["t547"]

font:
  - file: "gfonts://Roboto"
    id: font_title
    size: 52

  - file: "gfonts://Roboto"
    id: font_subtitle
    size: 32

display:
  - platform: t547
    id: my_display
    update_interval: 10s
    rotation: 180
    lambda: |-
      const int w = it.get_width();
      const int h = it.get_height();

      it.fill(COLOR_OFF);
      it.rectangle(10, 10, w - 20, h - 20);

      for (int x = 20; x < w - 20; x += 40) {
        it.line(x, 30, x + 20, 30, COLOR_ON);
      }

      for (int i = 0; i < 40; i += 4) {
        it.line(20 + i, 20, 20, 20 + i, COLOR_ON);
      }

      it.printf(w / 2, h / 2 - 40, id(font_title), TextAlign::CENTER, "ESPHome T547");
      it.printf(w / 2, h / 2 + 10, id(font_subtitle), TextAlign::CENTER, "Hello world!");
